### ISSUE TITLE
--tsv includes the event url

### ISSUE THREAD

**Issue by empierre** [insanum/gcalcli#173]
Hello,

  in version 3.1 when I add the --tsv I get the URL added to the list which is not intended: 

gcalcli --nocolor --nostarted agenda 
Fri Jan 16  07:00  PIR=Off

gcalcli --nocolor --nostarted --tsv agenda 
2015-01-16	07:00	2015-01-16	08:00	https://www.google.com/calendar/event?eid=xxx		PIR=Off

**Comment by tresni** [comment]
Adding event URLs has been around since 2.4 (specifically [commit 324f03da](https://github.com/insanum/gcalcli/commit/324f03da83ddd4ce726152d8027fa4928bc1ee9d#diff-26677a809224f66dae0eb20d234bca72R857)).  3.2 (as of 013d5dcdeefe79379365d3c5c61dedd6d09c1a5e) now allows you to control which fields you want in the tsv output using the `--details` options.  By default we are back to only showing start time, stop time and title.
