### ISSUE TITLE
Any way to show calendars from multiple accounts?

### ISSUE THREAD

**Issue by cache-return** [insanum/gcalcli#292]
Is there a way to display calendars from multiple google accounts?  I don't see any functionality for this, but I'm willing to hack it a little if someone has figured out a way.

**Comment by Purgator** [comment]
Yep and it's easy, just create a folder to store the configuration of your second account.
Mine is ~/.gcalcli-perso 
Then you can call it by using the following :

gcalcli --configFolder ~/.gcalcli-perso

You may probably initialize it with list :
gcalcli --configFolder ~/.gcalcli-perso

It shoud populate your directory, I'm not sure while i did this only 2 times in my life.

**Comment by cache-return** [comment]
That allows one gcalcli calendar per account, but is there a way to draw calendars from two accounts to the same gcalcli calendar?  I want something like:

gcalcli calm --configFolder ~/.gcalcli-perso --configFolder ~/.gcalcli-work

but as far as I can tell, there is not this kind of functionality.

**Comment by Purgator** [comment]
If I understand right, you want to see all event from both calendars, drawed in the same square ? You want to fuse both calendar as like they are only 1 calendar.
That not possible by design, it's not the purpose.

There is 2 solutions BTW :  
- Use a wrapper around gcalcli that can display several calendars. (that probably doesn't exist yet)
- Create a specific google calendar and add both calendars to it. Then call this account from gcalcli.

Just my 2 cents.

**Comment by thapakazi** [comment]
the thing I was struggling with too... and i have to bash it quick :neckbeard:  [like](https://github.com/thapakazi/kutto_kodalo/blob/gumantae/shellrc.d/business.sh#L3-L10)
```bash
# asssuming you have set your config folders inside this folder
GCALCLI_CONFIG_DIR=$HOME/.gcalcli

# generic function to do same thing on both of the servers
# default: is to list the agenda
gcalcli_all(){
    action=${1:-agenda}
    ls -1 $GCALCLI_CONFIG_DIR | xargs -I {} gcalcli --configFolder $GCALCLI_CONFIG_DIR/{} ${action}
}
``` 

Though it doesn't show the stuffs the way we desireds, i will live with it for a while 😃
