### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by sens** [insanum/gcalcli#325]
Gcalcli has been working flawlessly for quite some time for me now -- thank you!  After a recent update (via Debian), I have noticed import errors.  The other functions (creating events, getting agenda, etc) are working.

    % gcal import -d event.txt
    Traceback (most recent call last):
    File "/usr/bin/gcalcli", line 2500, in <module>
        BowChickaWowWow()  
      File "/usr/bin/gcalcli", line 2490, in BowChickaWowWow
        gcal.ImportICS(FLAGS.verbose, FLAGS.dump, FLAGS.reminder, FLAGS.file)
    AttributeError: 'Namespace' object has no attribute 'reminder'`

**Comment by sens** [comment]
Attached is the event file (Outlook) edited to remove personal details.
[event.txt](https://github.com/insanum/gcalcli/files/1438589/event.txt)

**Comment by pjweisberg** [comment]
I have no idea how to fix this problem, but you can use `pip` to downgrade to an older version that doesn't have it.  I think Debian must have moved to the alpha release 4.0.0a3 because 3.4.0 depends on a (very) old version of oauth2client and they wanted a newer one for their distro.

Something like this should get you back up and running with v3.4.0.
```
apt-get install python-pip
pip install gcalcli
echo 'PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
```

**Comment by michaelmhoffman** [comment]
I think the line

```
_import = sub.add_parser("import")
```
should instead be

```
_import = sub.add_parser("import", parents=[remindParser])
```

Additionally, the line

```
gcal.ImportICS(FLAGS.verbose, FLAGS.dump, FLAGS.reminder, FLAGS.file)
```
passes an `argparse.FileType` object but a file name seems to be expected. Changing `FLAGS.file` to `FLAGS.file.name` seems to fix it.

**Comment by sens** [comment]
Thank you @michaelmhoffman. I can confirm that your change fixes the problem.

@pjweisberg: Thanks for your response.  Downgrading to v3.4.0 was my temporary solution.

**Comment by eMPee584** [comment]
Mh, that fix wasn't enough for me.. 
`Error: name 'file' is not defined!` => replaced `file()` call with `open()` — but then another one:
```
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2500, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2490, in BowChickaWowWow
    gcal.ImportICS(FLAGS.verbose, FLAGS.dump, FLAGS.reminder, FLAGS.file.name)
  File "/usr/bin/gcalcli", line 2060, in ImportICS
    v = vobject.readComponents(f).next()
AttributeError: 'generator' object has no attribute 'next'
```
This is debian gcalcli 4.0.0~a3-1 python3 version. Here's a failing file:
[DSC-Notes-15012018 (1).ics.txt](https://github.com/insanum/gcalcli/files/1633137/DSC-Notes-15012018.1.ics.txt)

**Comment by michaelmhoffman** [comment]
That's another thing that's changed in Python 3. I have it working on Python 2. Looks like the whole `import` subcommand might not have been tested for  the conversion to Python 3.

**Comment by sens** [comment]
Confirming both @michaelmhoffman and @eMPee584 observations.  I am using it with Python2 and it's working now.

**Comment by jcrowgey** [comment]
Closing since it appears that @michaelmhoffman fixed this.

**Comment by l0ddej0kk0** [comment]
Installed 4.0.0a3 via apt-get: Got that import error above.
Removed it, pip-installed v3.4.0: Got [https://github.com/insanum/gcalcli/issues/338](url).
pip-installed vobject: Imported OK.

My .gcalclirc, anonymized:
`
--defaultCalendar=myemailadr@googlemail.com
--client_id=###myapikey###.apps.googleusercontent.com
--client_secret=###mysecret###
`

Since there are several Python releases installed here, i don't know which one gcalcli uses. Sorry.
-- 
regards,
-- wolflike

**Comment by jcrowgey** [comment]
Sorry, I'm not sure if I understand.  You're reporting that you get the import error when using python3, is that correct?  It seems like it might be good to get 4.0.0a5 into the Ubuntu release instead of a3, as several bugs were fixed.

I believe that this was fixed in af061db5 (#357) when I moved the next call to six.

**Comment by l0ddej0kk0** [comment]
Hi,
as i said, i don't know. How would i determine the Python version used by gcalcli, with several different installed?

Also, i forgot to mention, i'm using Debian Testing, and the 4.0.0a3 came from Debian repos.
I see now in [https://packages.debian.org/cgi-bin/search_packages.pl?keywords=gcalcli&searchon=all&subword=1&case=insensitive&version=all&release=all](url), (Ubuntu ditto) that a4 has become available. Now where would i get a 4.0.0a5 DEB package from?

-- 
regards,
-- wolflike

**Comment by jcrowgey** [comment]
Hi, there may not be a deb package yet for 4.0.0a5.  But you could git-clone this repo and run the latest code in a virtual environment with a python of your intentional choice.

If you didn't want to go that route, I'm reasonably sure that gcalcli is just going to run using your system's default python, so just type "python" at a command prompt and see what version starts.  But really, the question to you is whether you're using a version which imports `next` from six (to provide compatibility with both python2 and python3).  If you just want to find that out find the location of the gcalcli executable and grep for "next", if you find the line which looks like this:

```
    from six import next
```

then I'll eat my hat and I'll have to try to fix your bug!

**Comment by l0ddej0kk0** [comment]
Hi,
well, as i said, i'm making do with 3.4.0, which until now works Ok for me.
Maybe i'll try the Github version some time later.

Apparently, my default python version is
`$ python
Python 2.7.15+ (default, Aug 31 2018, 11:56:52) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> `.
For some reason, i'm unable to locate 4.0.0-a3 anwhere; the -a4 available indeed does not have any `from six import next` or words to that effect. Your hat gets a temporary reprieve.

-- 
regards,
-- wolflike
