### ISSUE TITLE
Importing gcalcli via python?

### ISSUE THREAD

**Issue by oppsig** [insanum/gcalcli#364]
Is it possible to import gcalcli as a module in a python script and add events to calendar? I'm guessing since it python this would be possible but could you provide an example in doing this if possible? Need to generate a lot of events. I haven't studied the internal classes of gcalcli.

**Comment by tresni** [comment]
The short answer is no. You would better off leveraging the google api python libraries.

**Comment by jcrowgey** [comment]
@oppsig: I want to slightly differ from @tresni here.  If you look at gcalcli/tests/test_gacalcli you'll see how to import and instantiate the GoogleCalendarInterface.  After that, you can call AddEvent programmatically as you please.  If you want to actually insert to a real calendar that you own and have access to, then you obviously woudn't want the monkeypatching.  Nevertheless, the imports and function calls in the test_gcalcli.py file should provide you a model for what you're trying to do.

My hope is that in the future we'll have a nice clean separation between our cli code and our "backend"  code which communicates with the Google APIs.  This is in part so that people can use the tool interactively or programmatically.   That's my vision, anyway, I can't speak for others.
