### ISSUE TITLE
Python error installing with apt-get on Ubuntu: SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by Vichoko** [insanum/gcalcli#365]
I installed gcalcli with ```sudo apt-get install gcalcli``` and when i run it, it throws this error:

```
File "/usr/bin/gcalcli", line 196
    print "ERROR: Missing module - %s" % e.args[0]
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "ERROR: Missing module - %s" % e.args[0])?
```

I know it might be a problem because i have my python name binded to Anaconda's Python 3.6.3, and the sources include old styled prints.

I suggest making gcalcli more reliable to this cases because older versions of python will be less supported as the time passes.

**Comment by jcrowgey** [comment]
@Vichoko I can replicate this when I run gcalcli version 3.4 (the version in debian stable package manager) using python3.5.  On debian, gcalcli is installed by the package manager at /usr/bin/gcalcli.  And if, depsite the fact that the system's default python is python2.7, i do something like this:

```
$ python3 /usr/bin/gcalcli
```

Then I can get the same error (albeit on a different line)

```
  File "/usr/bin/gcalcli", line 200
    print "ERROR: Missing module - %s" % e.args[0]
                                     ^
SyntaxError: Missing parentheses in call to 'print'
```

Nevertheless, if you pip install from master in this repo (which is currently 4.0.4alpha):

```
$ git clone github.com/insanum/gcalcli
$ python3.6 -m venv venv
$ . venv/bin/activate
$ pip install -I .
$ gcalcli --help
```
Then you'll be able to run gcalcli under python3 (it's also backwards compatible with python2.7) and you'll alse be able to help us report bugs in the alpha version.

I'm going to close this ticket because we *do* support python3 in the next release.  If you find bugs running the upcoming gcalcli against python3, please don't hesitate to report them!
