### ISSUE TITLE
raw_input usage in python3 version of code

### ISSUE THREAD

**Issue by zyehia** [insanum/gcalcli#370]
Hi there,

I noticed that, when trying to delete a task in the python 3 version of the code, I was getting an error from the usage of the `raw_input()` funcition in the `/usr/bin/gcalcli` file. 

`raw_input()` has been replaced by `input()` in python3, so I simply just replaced all instances of raw_input with input in that file to fix it with a vim substitution:

:%s/raw_input/input/g

It now work great :)

Hope this helps!

**Comment by jcrowgey** [comment]
Hi there,

I guess you're not on current master.  Line 77 of gcalcli.py:

```
    from six.moves import input, range, zip, map, cPickle as pickle
```

You'll find that all references to `raw_input` have already been replaced with `input`, and because we have overridden `input` with `six.moves.input`, we should be compabile with py27 as well.

In general, we are now using six to write code which should be py27,py3K compatible.  If you find issues in 4.0.0a5 or later which aren't python2.7 and python3.x compatible, let us know!
