### ISSUE TITLE
README usage message is out of date for 4.0.0 release

### ISSUE THREAD

**Issue by zyehia** [insanum/gcalcli#371]
Hi there,

In the documentation it says that we can add a detailed task like so:

gcalcli --calendar 'Eric Davis'
                                      --title 'Analysis of Algorithms Final'
                                      --where UCI
                                      --when '12/14/2012 10:00'
                                      --duration 60
                                      --description 'It is going to be hard!'
                                      --reminder 30
                                      --who 'boss@example.com'
                                      **add**

This implies that the add keyword comes at the end of the command.

This gave me an error saying:

` gcalcli: error: argument command: invalid choice: 'Analysis of Algorithms Final' (choose from 'list', 'search', 'agenda', 'calw', 'calm', 'quick', 'add', 'delete', 'edit', 'import', 'remind')`

To fix this, we need to put the add keyword right after the calendar specification

like so:

gcalcli --calendar 'Eric Davis' **add**
                                      --title 'Analysis of Algorithms Final'
                                      --where UCI
                                      --when '12/14/2012 10:00'
                                      --duration 60
                                      --description 'It is going to be hard!'
                                      --reminder 30
                                      --who 'boss@example.com'

Changing the documentation to reflect this correct positioning would be very useful!

Best wishes

**Comment by jcrowgey** [comment]
You're right that the documentation on the arguments is probably out of date, even on the current development version.  To catch you up, we have moved to using argparse instead of gflags for command line options and argument processing.  This is actually the major change intended for 4.0.0 release.  Figuring out the right way to port our code to argparse while maintaining backwards compatibility as much as possible is still a work in progress.  If you can help us test 4.0.0a5 or later and report issues, we'd be very happy for those reports.

**Comment by martonbalazs** [comment]
Hi, I'm very grateful for gcalcli and it's really nice that you wrote and mantain it but just so that you know I've spent almost 6 hours banging my head into the wall and trying every possible things I could just think of to figure out how on Earth my script with gcalcli in it just stopped working from one day to the other -- before I found this notice hidden here.

**Comment by hammerheadlemon** [comment]
For the record, I support the view that making a change to the README sooner rather than later will be helpful - taking into account @jcrowgey's points. The docs are pretty confusing at the moment - I too spent a long time trying to work out where the command/options are supposed to go. It looks like there is a fair amount of work to do to get a good 4.0 release out the door, but I think this should be prioritised. Users can easily be put off immediately if the docs are clearly wrong. Happy to contribute.

**Comment by jcrowgey** [comment]
Yes, I'm happy to accept PRs which get the docs into shape.  Possibly related, if you're going to touch the argument_parsers module and docs is #363 and #347

**Comment by jcrowgey** [comment]
I've made an effort this.  Merged as 9cf983a.

Of note, I removed most of the details from the usage section in the README.  I put *some* into the man page.  I added a lot of the detail in the README to the 'help' and 'description' properties of the subcommands so that the online -h/--help is hopefully much better now.

We may want to add particular example usage back at some point, but I'd like to focus on doing that in one spot (prefer the man page, eventually keeping the README focused on installation).  In the mean time, the out-of-date documentation was particularly bad for new users, so i think it's better to have less for now and ensure that what we have is actually up-to-date.
