### ISSUE TITLE
Specify color for specific event?

### ISSUE THREAD

**Issue by naquad** [insanum/gcalcli#393]
In my case I'm trying to stuff multiple events into calendar and then view it in browser. It would be awesome if add would support something like `--color-id` for individual event.

Predefined list of colors can be found in API: https://developers.google.com/calendar/v3/reference/colors/get

and set as colorId attribute for event (https://developers.google.com/calendar/v3/reference/events/insert )

**Comment by hammerheadlemon** [comment]
I'd find this useful too.  A `--colorId` argument to `quick` and `add` using the current colour list https://developers.google.com/calendar/v3/reference/colors/get. Invalid colours ignored and revert to default.

I'd be happy to submit a PR if maintainer is interested in adding that functionality?

**Comment by jcrowgey** [comment]
@hammerheadlemon I don't see any harm in that.  Please take a look at #382, however, because I'd like to eventually remove all the random camelCasing.

**Comment by jcrowgey** [comment]
Two more quick comments and a request:

1) take a look at integration with the existing color stuff that's available on subcommands that take output_parser;  it looks like we current output colors based on the calendar.  will your option to output per event override the calendar's color?  or maybe you're thinking that this color will be ignored in cli printing, but just used to set the variable that browsers may respect (in re the OP of this issue)?  I think either way may be fine, but that may affect how you name the option.

2) the existing options use the u-less spelling, but if you wanted to, I'd be fine with adding alternative spelling flags as well.  Ideally, we could get this to print in the --help as something like:

--colo[u]r DESCRIPTION

so that the help message wouldn't have twice lines.  Another idea would just be to add nohelp to the u-full options so that they're like a shadow feature.  A third alternative, if you really want to get fancy: we are already doing stuff that reads the locale, so you could actually set up the program to use u-full options by default but switch to u-less options in US locales.  Anyway, have fun and thanks for taking a look.

A request: most of these flags have _ between words.  But it's much more traditional in unix cli programs to use a - in long option names.  I'd like to go ahead and start standardizing (standardising? :)), so if you do submit a pull request with some sort of --colo[u]r stuff, maybe you could switch the related color options to use hyphen instead of underscore.

**Comment by hammerheadlemon** [comment]
Originally my thought was to implement for the browser only, but I'll take a look at what's involved to reflect any imparted colour in the terminal too. A quick look suggests it might work just fine, but I'll take a look.

There is a potential dependency (both in documentation, in `--help` and the code itself) on what colours/colour names Google are currently making available to use for this purpose. A potential way round that might be something like a new `checkcolours` command that queries the API (https://developers.google.com/calendar/v3/reference/colors) and provides the necessary strings needed for the `--colo[u]r` option. That would at least minimise future API changes, but I guess API dependency is an issue for `gcalcli` throughout anyway, so no big deal perhaps.

I will also look at using the hypens as per unix cli tradition. I'd much prefer that.

Thanks for your views on the use of `u` in `col[u]r`!

Looking to work on the PR this weekend.

**Comment by hammerheadlemon** [comment]
Please see PR #397

**Comment by jcrowgey** [comment]
Thank you for the work!  I've taken a quick look and there are a few things I'd like to address before we merge it.

**Comment by hammerheadlemon** [comment]
Updated PR.

**Comment by jcrowgey** [comment]
Fixed in #397 (thanks @hammerheadlemon!)
