### ISSUE TITLE
Colors on Conky mode don't work

### ISSUE THREAD

**Issue by hrqmonteiro** [insanum/gcalcli#424]
With the --conky option, no matter which colors i have on my conkyrc, the agenda or calendar just shows yellow and blue
![2019-02-23-204320_326x143_scrot](https://user-images.githubusercontent.com/17055027/53293054-aba28180-37ab-11e9-88a3-ff3da628d97a.png)

**Comment by jcrowgey** [comment]
Can you say what version you're on (and what version of Python?).

FWIW, I *can* seem to set the colors just fine using conky mode in the conky file:

```
${execpi 1000 gcalcli --lineart=ascii --conky agenda --color-date=red} 
```

^^^ that works just fine for me to make the dates red, for example.  So it may be that the issue is specific to the interaction with the config file.

**Comment by lasers** [comment]
Your example code worked okay on conky. `color-date`, `color-owner`, and `color-reader` worked okay on conky too.

Maybe OP was trying the conky color codes instead of gcalcli color args? He/she should disable gcalcli colors to use conky color code, otherwise default colors would be used same as the screenshot.
```bash
# conky.conf
...
${color orange}${execpi 600 gcalcli --nocolor --conky agenda}{color}
]]
```

**Comment by Asitis** [comment]
Setting `color-date=red` would work, but it only works with preset determined basic colors in gcalcli like red, green, blue, yellow and white. It would be nice/expected/awesome to be able to use just hex-colors, because all the primary colors look, well, awful.
