### ISSUE TITLE
changing the date format output

### ISSUE THREAD

**Issue by aristosv** [insanum/gcalcli#456]
I am currently using this command to view my calendar events.

`gcalcli agenda --tsv "$datenow" "$date24hrs"`

The date i shown in this format

`2019-06-05`

Is there a way to make it appear like this?

`05-06-2019`

The reason I am asking is because this date will be placed in a variable and sent out to customers using SMS. In Europe this is the standard format for dates, so I don't want them to be confused.

**Comment by aristosv** [comment]
I solved it like this

`awk -F'[- ]' '{ print $3"-"$2"-"$1" "$4" "$5 }'`

**Comment by jcrowgey** [comment]
Yes, post processing what you need to do for now, since the output format is hard-coded:

https://github.com/insanum/gcalcli/blob/e5d2f94160c900b183f96930f6f1e8fd0840f337/gcalcli/gcal.py#L594
https://github.com/insanum/gcalcli/blob/e5d2f94160c900b183f96930f6f1e8fd0840f337/gcalcli/gcal.py#L1014

There has been some discussion about pulling the output format from the locale, I would be interested in such a pull request if you're up for it.

**Comment by aristosv** [comment]
I wish I had some idea on how to do that :)
