### ISSUE TITLE
calw only retrieve the first week of the month

### ISSUE THREAD

**Issue by olivier-klein** [insanum/gcalcli#469]
I have installed the recent version of gcalcli 4.0.4. I observe weird behavior while trying to retrive the weekly calendar. The output is restricted to the first week of the month. I cannot retrieve 2 weeks consecutive : gcalcli calw 2 only display the first week of the month.
For infos gcalcli calm seems to work properly.
Best,
Olivier

**Comment by jcrowgey** [comment]
Hi, the --help is your friend.

```
~$ gcalcli --version
gcalcli v4.0.4 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)
~$ gcalcli calw --help | grep -A2 positional
positional arguments:
  start
  weeks
```

So if you say something like `gcalcli calw 2` you're asking gcalcli to show you 1 week starting with the week that includes the 2nd of the month.

```
$ gcalcli --lineart=ascii calw 2 | head -n4
+----------+----------+----------+----------+----------+----------+----------+
|Sunday    |Monday    |Tuesday   |Wednesday |Thursday  |Friday    |Saturday  |
+----------+----------+----------+----------+----------+----------+----------+
|30 Jun    |01 Jul    |02 Jul    |03 Jul    |04 Jul    |05 Jul    |06 Jul    |
```

If you say `gcalcli calw 16`, you're asking gcalcli to show you 1 week starting with the week that includes the 16th:

```
$ gcalcli --lineart=ascii calw 16 | head -n4
+----------+----------+----------+----------+----------+----------+----------+
|Sunday    |Monday    |Tuesday   |Wednesday |Thursday  |Friday    |Saturday  |
+----------+----------+----------+----------+----------+----------+----------+
|14 Jul    |15 Jul    |16 Jul    |17 Jul    |18 Jul    |19 Jul    |20 Jul    |
```

If you want to show two weeks, you need the second positional arg to be set, which means you need to set the first one to something (any day this week will do)

```
$ gcalcli calw $(date +%d) 2
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│Sunday    │Monday    │Tuesday   │Wednesday │Thursday  │Friday    │Saturday  │
├──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│28 Jul    │29 Jul ** │30 Jul    │31 Jul    │01 Aug    │02 Aug    │03 Aug    │
│          │          │          │          │          │          │          │
├──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│04 Aug    │05 Aug    │06 Aug    │07 Aug    │08 Aug    │09 Aug    │10 Aug    │
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
```

Now, maybe we should decouple these so that they're not both positional args, but that's another question.

**Comment by olivier-klein** [comment]
Thanks a lot! How silly of me to have missed this modification.
O

Le mar. 30 juil. 2019 à 00:22, Joshua Crowgey <notifications@github.com> a
écrit :
