### ISSUE TITLE
ImportError: cannot import name get_terminal_size

### ISSUE THREAD

**Issue by ZaxonXP** [insanum/gcalcli#484]
Tried to install from pip on Debian 10 machine. It did install but when executing `gcalcli` I am getting following message:

```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 6, in <module>
    from gcalcli.cli import main
  File "/usr/local/lib/python2.7/dist-packages/gcalcli/cli.py", line 30, in <module>
    from gcalcli.argparsers import get_argument_parser, handle_unparsed
  File "/usr/local/lib/python2.7/dist-packages/gcalcli/argparsers.py", line 8, in <module>
    from shutil import get_terminal_size
ImportError: cannot import name get_terminal_size
```

Tried to install `shutil` but I got the error:

```
sudo pip install shutil
Collecting shutil
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/shutil/
```

Did a search in the Debian repository:
```
sudo apt search shutil
Sorting... Done
Full Text Search... Done
python-backports-shutil-get-terminal-size/stable,stable,stable,stable 1.0.0-5 all
  Backport of the "shutil.get_terminal_size" function (Python 2)
```
found the package and installed, but this did not help to resolve the issue.

Any idea what do I miss?

Regards,
Piotr

**Comment by ZaxonXP** [comment]
I found that if I use `sudo pip3 install gcalcli --upgrade` then there is no more issue.

**Comment by jcrowgey** [comment]
`shutil` is part of the standard library, I believe.  If that isn't the case then we ought to add it to the install_requires in setup.py

**Comment by ZaxonXP** [comment]
@jcrowgey: It wasn't in my case, so maybe it is good idea to add it according to your suggestion.

**Comment by jcrowgey** [comment]
So, here's what happened:

You said that things worked for you after doing pip3 install, which effectively switched you to python3.  That's a good thing really, it was time to do that anyway since Python2 is at EOL in about 3 months.  Anyway, if you look closely at your traceback, it doesn't say that it can't find `shutil`, it says it can't find the name `get_terminal_size`.  In fact, comparing the shutil docs between [python2] and [python3], it looks like `get_terminal_size` was added in 3, which explains your experience.

[python2]: https://docs.python.org/2/library/shutil.html
[python3]: https://docs.python.org/3/library/shutil.html

**Comment by ZaxonXP** [comment]
OK. Thanks for the explanation. :)
