### ISSUE TITLE
Add `python_requires` to `setup.py`

### ISSUE THREAD

**Issue by michaelmhoffman** [insanum/gcalcli#536]
gcalcli no longer works with Python 2. This should be specified in package information. To do this, add something like `python_requires='>=3'` to `setup.py`. Testing is only done with Python >=3.5, so if that is the requirement, add `python_requires='>=3.5'` and it should also be specified in `README.md`.

**Comment by jcrowgey** [comment]
Yes please!

**Comment by michaelmhoffman** [comment]
Are there any 3.5-only features? What should the minimum version be? Will it work with `>=3`?

**Comment by jcrowgey** [comment]
I don't know of any >= 3.5 features.  I started with 3.5 in the tox setup, iirc, because that was the Python3 interpreter I had available on my laptop at the time I started maintaining gcalcli.  I've just added future versions as they've become available.  I'd suggest >=3 as a starting point and if someone raises an issue with compatibility on some some 3 >= Python <= 3.5 then we can either be more precise about min Python version or fix their issue.
