### ISSUE TITLE
Nuisance warnings from tox

### ISSUE THREAD

**Issue by michaelmhoffman** [insanum/gcalcli#554]
On my system (Ubuntu 20.04 on WSL2) I get two warnings when starting tox.

1. `Warning: No long description generated.`
2. `UserWarning: Normalizing 'v4.3.0' to '4.3.0'`

```
$ tox
Warning: No long description generated.
/mnt/c/Users/mhoffman/src/collab/gcalcli/.tox/py35/lib/python3.5/site-packages/setuptools/dist.py:476: UserWarning: Normalizing 'v4.3.0' to '4.3.0'
  normalized_version,
```

**Comment by jcrowgey** [comment]
Both of these are related to package building.  The former is an
important one because we want to make sure we generate the
long-description before pushing a package to pypi.

On Mon, Aug 03, 2020 at 01:17:06PM -0700, Michael Hoffman wrote:
> On my system (Ubuntu 20.04 on WSL2) I get two warnings when starting tox.
> 
> 1. `Warning: No long description generated.`

This is because we build the long description from the README file using
pypandoc (iirc) when we release using an external module (pypandoc), see
setup.py.  If you're just building the package for testing (like tox
does), no one really needs to read the long description.  You might be
able to avoid the warning by putting pypandoc in the tox
requirements---but then you'll have a kind of unnecessary dependency for
simply running tests.

> 2. `UserWarning: Normalizing 'v4.3.0' to '4.3.0'`

Conventions differ across codebases and languages as to whether or not
semvers bear a preceding v.  For Python, this is unusual, and so
setuptools are letting us know that.  gcalcli was using the preceding
'v' on its version tags before I came to the project.  It might be nice
to drop the preceding 'v' in setup.py.  That would allow us to keep the
project tradition with respect to git-tags and to build Python packages
without complaints about the versions.


version = __version__[1:] if __version__.startswith('v') else __version__

**Comment by michaelmhoffman** [comment]
Thanks, making a `tox.local.ini` with added dependency on `pypandoc` and using `tox -c tox.local.ini` fixes the first problem.

Your solution to problem 2 looks good to me.

**Comment by dbarnett** [comment]
I updated setup.py and files for metadata/packaging, suspect both of those issues are obsolete now.
