### ISSUE TITLE
Initial setup is long.

### ISSUE THREAD

**Issue by martinmake** [insanum/gcalcli#572]
You could probably use PKCE: https://tools.ietf.org/html/rfc7636
Then the user will not have to get and store the secret key and they'll still be able to get a refresh token.
Another plus is that you will get to see usage metrics in your dashboard.

**Comment by dbarnett** [comment]
Do you know if this still applies if each user needs to set up their own oauth client with its own ID/secrets?

AFAICT it's not a viable option anymore to maintain a single shared client ID everyone can use due to Google's usage limits and security restrictions. In that model the Cloud Console setup has to be manual instructions AFAIK, and the one bit of somewhat annoying copy-paste is copying over client-id/client-secret [after creating auth client & token](https://github.com/insanum/gcalcli/blob/main/docs/api-auth.md#last-part-gcalcli-auth-setup), but I'm not following if PKCE offers a way to streamline just that step.

**Comment by dbarnett** [comment]
Closing as infeasible.

If anyone has details on how we could actually use PKCE in practice or other ways to streamline setup, please follow up here or in some other issue.

**Comment by dardo82** [comment]
Would this help?
https://github.com/copilot/share/0a1d1112-49e0-8880-9113-384860c04843

**Comment by dbarnett** [comment]
Yes, some. Installing gcloud cli can be kind of a pain in itself and there are probably a few usability challenges to making a tool easier for everyone to use than just following written instructions. But if you want to implement a version of the setup command that shells out to gcloud I think that could be useful.

**Comment by dardo82** [comment]
But did you try the suggested commands?
What's wrong or missing in this script?

**Comment by dbarnett** [comment]
No, I just read through the script, and from that I don't see anything outright missing. If anyone is setting up gcalcli from scratch and wants to try it out I'd encourage them to try it and report back if it saved them hassle.

If instead of supplying it as an optional helper the goal is to REPLACE all the existing instructions with the script then some users who struggle with setup may get stuck worse running the script as-is (figuring out deps and input values to patch in) than they would just manually following instructions. That could probably be improved by converting from a bash script to a gcalcli command with nice user prompting and error messaging though if someone wanted to spend time making a friendly implementation though.

**Comment by dardo82** [comment]
Things that doesn't exist can't break.

**Comment by mdengler** [comment]
For future reference, it looks like PKCE support in python from google has gone through a few iterations and is now at [oauthlib](https://oauthlib.readthedocs.io/en/latest/faq.html)
