### ISSUE TITLE
I keep having to renew

### ISSUE THREAD

**Issue by matheusfillipe** [insanum/gcalcli#603]
From time to time, about once per week, it fails to show my agenda saying I have to auth again and after I do this it works again. 

I did just as in here to create my own google app id and key for this: https://github.com/insanum/gcalcli#login-information. 

Could it be that there is some expiry time I am not aware of? What can be happening here?

**Comment by safijari** [comment]
I have the same issue

**Comment by aristosv** [comment]
did you ever find a solution to this issue? I have the same issue also.

**Comment by ajkessel** [comment]
Per https://github.com/insanum/gcalcli/issues/611 , if we can figure out how to get gcalcli to pass a redirect_uri parameter to the Python Google OAuth2 module, it should be possible to publish the app without Google review and have longer-lasting tokens. I also filed an Ubuntu bug report at https://bugs.launchpad.net/ubuntu/+source/python-oauth2client/+bug/1983216 since it appears upstream is no longer maintaining the relevant library https://github.com/googleapis/oauth2client/issues/317

**Comment by dbarnett** [comment]
I'm assuming that's similar to how other projects like https://github.com/mbrt/gmailctl are doing the auth? I use that project too and I don't think I've ever had to reauth like that.

**Comment by dbarnett** [comment]
Likely fixed now that I merged https://github.com/insanum/gcalcli/pull/683. Please let me know if issues remain. Thanks!
