### ISSUE TITLE
agendaupdate should be able to create new events vs. just updating existing events

### ISSUE THREAD

**Issue by dbarnett** [insanum/gcalcli#772]
Would be nice to be able to create new events in batch using a mechanism similar to the agendaupdate command.

Per https://github.com/insanum/gcalcli/issues/550#issue-656847840, it can currently update existing events but is missing:

 - A feature to add new events through this interface instead of only updating events with existing IDs

@michaelmhoffman

**Comment by michaelmhoffman** [comment]
I added an `insert` action that does this years ago, and it is already released. How to use:

1. Run `gcalcli agenda --tsv` with `--details action` included.
2. Make a new row, leaving `id` empty, and setting `action` to `insert` instead of the `patch` provided for existing objects.

**Comment by michaelmhoffman** [comment]
I added an `insert` action that does this years ago, and it is already released. Unfortunately, I did not edit GitHub issues at the time to make this clear.

How to use:

1. Run `gcalcli agenda --tsv` with `--details action` included.
2. Make a new row, leaving `id` empty, and setting `action` to `insert` instead of the `patch` provided for existing objects.
