### ISSUE TITLE
Startup fails with 'ERROR: Missing module - No module named discovery'

### ISSUE THREAD

**Issue by mstyne** [insanum/gcalcli#86]
It's probably just a matter of having the right module installed, but I don't seem to be able to track it down.

```
$ pip install discovery
Downloading/unpacking discovery
  Could not find any downloads that satisfy the requirement discovery
No distributions at all found for discovery
Storing complete log in /Users/mstyne/Library/Logs/pip.log
```

Any idea where/what this module is actually named?

**Comment by jdams051** [comment]
Substitute in the executable
# bad
from apiclient.discovery import build

# good
from googleapiclient.discovery import build

**Comment by tresni** [comment]
@jdams051 sounds like something changed in a newer version of google-api-python-client.  May need to pin that package like we do oauthclient to keep things working.

**Comment by bug0000** [comment]
Does anyone know how to solve this problem?
Linux Mint 17
_ERROR: Missing module - No module named discovery_

**Comment by kdvolder** [comment]
What worked for me on Ubuntu 12.04 didn't on 14.04. I figured the problem is some mismatch between the default libs and python version installed on my system (Ubuntu 14.04) and the versions of those things the gcacli has been written and tested with. 

But I somehow got it to work by using virtualenv to give it exactly the version(s) needed.

I'd give you detailed instructions, but unfortunately I didn't write down all the steps. 

However, I'd recommend using virtual-env to control precisely the python environemt you run gcalcli with. That works for me and it has been stable and doing what I want it it to do for quite a while now (so long in fact I already forgot precisely what I did to make it work).

**Comment by kdvolder** [comment]
This might be useful if you want to explore using virtualenv: 
http://docs.python-guide.org/en/latest/dev/virtualenvs/

If I recall correctly I think I did something like this:

              virtualenv -p /usr/bin/python2.7 myenv

Then activated that env.

Then installed gcalcli in that env (which is far less cluttered with 'stuff' than the one you get from your Ubuntu).

And that sort of works. I don't remember doing anything more complex really. But its been a while ago.
